name: Build & Test API-1

on:
  push:
    branches:
      - feature/*
      - bugfix/*
      - hotfix/*
    paths:
      - 'packages/api-1/**'

jobs:
  build_and_test:
    uses: 'iago-srm/language-app/.github/workflows/reusable-build-and-test.yml@main'
    with:
      package: 'api-1'
